---
title: "R Notebook"
output: html_notebook
---

```{r}
library(rwebppl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggthemes)
```

We begin with the simple horn implicature model... 

```{r}
arbitrarinessModel2 <- function(alpha, beta) {
  res <- webppl(program_file = 'arbitrariness.wppl',
                model_var = 'model',
               inference_opts = list(method="forward", samples=100),
               data = list(alpha = alpha, beta = beta, numSteps = 6),
               data_var = 'params')
  accuracyRes = res %>%
    separate(Parameter, c('type', 'roundNum')) %>%
    mutate(alpha = as.character(alpha),
           beta = as.character(beta))

  return(accuracyRes)
}
arbitrarinessRes2 <- arbitrarinessModel(5,1)
```

```{r}
#arbitrarinessRes
arbitrarinessRes2 %>% 
  filter(type == 'acc') %>%
  group_by(roundNum, value) %>%
  tally() %>%   
  group_by(roundNum) %>%
  mutate(prob = n / sum(n)) %>%
  ungroup() %>%
  filter(value == TRUE) %>%
  mutate(roundNum = as.numeric(roundNum)) %>%
  ggplot(aes(x = roundNum, y = prob)) +
    ylab('accuracy') +
    xlab('round #') +
    geom_line() +
    geom_hline(aes(yintercept=.5), linetype = 2) +
    ylim(0,1) +
    theme_few(9) +
    theme( plot.margin=unit(x=c(0,0,0,0),units="mm"))
```

```{r}
arbitrarinessRes2 %>%
  spread(type, value) %>%
  unite(intendedPair, intended, utt, sep = '<->', remove = F) %>% 
  unite(realPair, utt, response, sep = '<->', remove = F) %>% 
  group_by(Iteration) %>% 
  mutate(firstPair = first(realPair)) %>%
  mutate(firstSystem = ifelse(firstPair %in% c('label1<->t1', 'label2<->t2'),
                         'system1', 'system2')) %>%
  mutate(chosenSystem = ifelse(intendedPair %in% c('t1<->label1', 't2<->label2'),
                         'system1', 'system2')) %>%
  group_by(firstSystem, roundNum, chosenSystem) %>% 
  tally() %>%
  ungroup() %>%
  complete(firstSystem, roundNum, chosenSystem, fill = list(n = 0)) %>%  
  group_by(roundNum, chosenSystem) %>%
  mutate(prob = n/sum(n)) %>%
  filter(chosenSystem == 'system1') %>%
  ggplot(aes(x = roundNum, y = prob, group = firstSystem, 
             linetype =firstSystem, color = firstSystem)) +
    ylab("S(label1 | t1) (expected)") +
    geom_line() +
    geom_point() + 
    theme_few(9) +
    theme( plot.margin=unit(x=c(0,0,0,0),units="mm"), 
           legend.margin=unit(0,"cm"),
           legend.position="top")
```


```{r}
lexicalizationModel <- function(alpha, beta) {
  res <- webppl(program_file = 'hornLexicalization.wppl')
  accuracyRes = res %>%
    separate(Parameter, c('type', 'roundNum')) %>%
    mutate(alpha = as.character(alpha),
           beta = as.character(beta))
  return(accuracyRes)
}
lexicalizationRes <- lexicalizationModel(10,1)
```

```{r}
lexicalizationRes %>% 
  filter(type == 'acc') %>%
  group_by(roundNum, value) %>%
  tally() %>%   
  group_by(roundNum) %>%
  mutate(prob = n / sum(n)) %>%
  ungroup() %>%
  filter(value == TRUE) %>%
  mutate(roundNum = as.numeric(roundNum)) %>%
  ggplot(aes(x = roundNum, y = prob)) +
    ylab('accuracy') +
    xlab('round #') +
    geom_line() +
    geom_hline(aes(yintercept=.5), linetype = 2) +
    ylim(0,1) +
    theme_few(9) +
    theme( plot.margin=unit(x=c(0,0,0,0),units="mm"))
```


```{r}
lexicalizationRes %>%
  spread(type, value) %>%
  unite(intendedPair, intended, utt, sep = '<->', remove = F) %>% 
  unite(realPair, utt, response, sep = '<->', remove = F) %>% 
  group_by(Iteration) %>% 
  mutate(firstPair = first(realPair)) %>%
  group_by(firstPair, roundNum, intendedPair) %>% 
  tally() %>%
  ungroup() %>%
  complete(firstPair, roundNum, intendedPair, fill = list(n = 0)) %>%  
  group_by(firstPair, roundNum) %>%
  mutate(prob = n/sum(n)) %>%
  filter(intendedPair == 'common<->cheap') %>%
  filter(firstPair %in% c('cheap<->common', 'expensive<->common')) %>%
  ggplot(aes(x = roundNum, y = prob, group = firstPair, 
             linetype =firstPair, color = firstPair)) +
    ylab("S(label1 | t1) (expected)") +
    geom_line() +
    geom_point() + 
    theme_few(9) +
    theme( plot.margin=unit(x=c(0,0,0,0),units="mm"), 
           legend.margin=unit(0,"cm"),
           legend.position="top")
```