---
title: "R Notebook"
output: html_notebook
---

# Imports

```{r}
library(tidyverse)
library(ggthemes)
library(tidyboot)
library(here)

clicks <- read_csv(here('./data/experiment3/clicks.csv'))
messages <- read_csv(here('./data/experiment3/messages.csv'))
completeNetworks <- clicks %>% 
  distinct() %>% 
  group_by(networkid) %>% 
  tally() %>%
  filter(n == 96) %>% 
  pull(networkid)

numParticipantsRecruited <- length(unique(clicks$participantid))

numNetworks <- length(completeNetworks)
relevantMessages <- messages %>% 
  filter(networkid %in% completeNetworks) %>%
  filter(role == "speaker") %>%
  group_by_at(vars(-content)) %>%
  summarize(content = first(content)) %>%
  mutate(uttLength = str_count(content, " ") +1,
         repnum = floor(trialnum / 4)) %>%
  rowwise() %>%
  mutate(repnum = repnum + 1) %>%
  group_by(participantid, partnernum) %>%
  mutate(ordinalrep = ifelse(repnum == min(repnum), 'first', 'second')) %>%
  group_by(participantid, trialnum, networkid, roomid, 
           target, partnernum, repnum, ordinalrep) %>%
  summarize(m = sum(uttLength)) %>%
  ungroup()

relevantClicks <- clicks %>%
  filter(networkid %in% completeNetworks) %>%
  mutate(repnum = floor(trialnum / 4)) %>%
  mutate(correct = object_id == 'target') %>%
  left_join(relevantMessages %>% 
              select(target, trialnum, networkid, roomid, ordinalrep) %>% 
              distinct(), 
            by = c( 'roomid', 'trialnum', 'networkid'))
```

# Num words

```{r}
messages.mean <- relevantMessages %>%
  group_by(partnernum, repnum) %>%
  tidyboot::tidyboot_mean(column = m)

results.plt2 <- messages.mean %>%
  mutate(t = repnum + 4 * partnernum) %>%
  ggplot(aes(x = t, y = empirical_stat, group = partnernum)) +
    geom_point() +
    geom_line() +
    scale_x_continuous(breaks = c(1,3, 5,7,9,11)) +
    geom_vline(xintercept = c(4.5, 8.5), lwd = .5, color = 'grey') +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width =0) +
    theme_few() +
    theme(aspect.ratio = 3/5) +
    guides(color = FALSE, fill = FALSE) +
    ylim(2,8) +
    labs(x = "time", y = "# words", tag = 'A')
```

### Convergence

```{r}
partnerLookup <- messages %>%
  group_by(networkid) %>%
  do(., mutate(., speakerID = group_indices(., participantid))) %>%
  group_by(networkid, roomid, partnernum, speakerID) %>%
  tally() %>%
  group_by(networkid, roomid) %>%
  mutate(partnerID = ifelse(speakerID == first(speakerID), 
                            last(speakerID), first(speakerID))) %>%
  ungroup() %>%
  mutate(speaker1 = as.factor(speakerID)) %>%
  select(-n, -roomid) 

stopwords_regex = paste(c('ive', tm::stopwords('SMART')), collapse = '\\b|\\b')
stopwords_regex = paste0('\\b', stopwords_regex, '\\b')

matches <- messages %>% 
  filter(role == "speaker") %>%
  filter(networkid %in% completeNetworks) %>%
  group_by(participantid, partnernum) %>%
  mutate(ordinalrep = ifelse(repid == min(repid), 'first', 'second'),
         content = tolower(content),
         content = stringr::str_replace_all(content, stopwords_regex, ""),
         content = str_squish(gsub("[[:punct:]]", "", content))) %>%
  group_by(networkid) %>%
  do(., mutate(., speakerID = as.integer(group_indices(., participantid)))) %>%
  group_by(ordinalrep, networkid, partnernum, stimsetid, repid, target, participantid, speakerID, trialnum) %>%
  summarize(content = paste0(content, collapse = ' ')) %>%
  group_by(networkid, repid, target, ordinalrep, partnernum, speakerID) %>%
  tidybayes::gather_pairs(speakerID, content, row = 'speaker1', col = 'speaker2', x = 'utt1', y = 'utt2') %>%
  left_join(partnerLookup) %>%
  rowwise() %>%
  mutate(partnerType = ifelse(speaker2 == partnerID, 'within', 'across'),
         matchRate = length(intersect(strsplit(utt1, " ")[[1]], strsplit(utt2, " ")[[1]])),
         utt1Length = length(strsplit(utt1, " ")[[1]]),
         utt2Length = length(strsplit(utt2, " ")[[1]])) %>%
  arrange(networkid, partnernum)

matches.summary <- matches %>% 
  group_by(partnernum,  partnerType) %>%
  tidyboot_mean(matchRate> 0)

results.plt3 <- matches.summary %>%
  # mutate(ordinalrep = ifelse(ordinalrep == 'first', partnernum*2,
  #                            partnernum*2 + 1)) %>%
  # ungroup() %>%
  mutate(comparison = ifelse(partnerType == 'within', 
                             'within dyad', 'across dyads')) %>%
  ggplot(aes(x = partnernum, y = empirical_stat)) +
             #group = interaction(partnernum, comparison))) +
    geom_point() +
    geom_line(aes(linetype = comparison)) +
    #geom_vline(xintercept = c(1.5, 3.5), lwd = .5, color = 'grey') +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    ggthemes::theme_few() +
    labs(x = "", y = "alignment") +
    ylim(0, 1) +
    scale_color_colorblind() +
    theme(aspect.ratio = 1, legend.position = 'none')
cowplot::plot_grid(results.plt2, results.plt3, ncol = 1, align = "vh")
ggsave('../writing/journal_manuscript/figures/sec3-empirical-results.pdf', 
       width = 3, height = 4, unit = 'in')
```

```{r}
library(lme4)
library(broom.mixed)
```

```{r}
glmer(match ~ partnernum * partnerType + (1 | target) + (1 + partnernum * partnerType | networkid), 
      family = 'binomial',
      control = glmerControl(optimizer = 'bobyqa'),
      data = matches %>% mutate(match = matchRate > 0)) %>%
  summary()

glmer(match ~ partnernum + (1 | target) + (1 + partnernum | networkid), 
      family = 'binomial',
      control = glmerControl(optimizer = 'bobyqa'),
      data = matches %>% mutate(match = matchRate > 0) %>% filter(partnerType == 'within') %>%  filter(partnernum < 2)) %>%
  summary()
```

# Supplementary 

## Accuracy results

```{r}
clicks.mean <- relevantClicks %>%  
  group_by(repnum, partnernum) %>%
  tidyboot::tidyboot_mean(correct)

results.plt1 <- clicks.mean %>%
  mutate(t = 1 + repnum + 4 * partnernum) %>%
  ggplot(aes(x = t, y = empirical_stat, group = partnernum)) +
    geom_point() +
    geom_line() +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width =0) +
    scale_x_continuous(breaks = c(1,3, 5,7,9,11)) +
    geom_vline(xintercept = c(4.5, 8.5), lwd = .5, color = 'grey') +
    theme_few() +
    theme(aspect.ratio = 3/5) +
    guides(color = FALSE, fill = FALSE) +
    labs(x = 'time', y = 'accuracy', tag = 'A')
```

```{r}
relevantClicks %>%  
  glmer(correct ~ repnum + (1 + repnum | participantid) + (1 + repnum |target),
              family = 'binomial',
              control = glmerControl("bobyqa"),
              data = .) %>%
  summary() 
```

accuracy drop at boundaries

```{r}
relevantClicks %>% 
  unite("key", partnernum, repnum) %>%
  select(networkid, target, correct, key) %>%
  group_by(networkid, target, key) %>%
  mutate(gameid = row_number()) %>%
  spread(key, correct) %>% 
  select(networkid, target, gameid, `0_3`, `1_0`, `1_3`, `2_0`) %>%
  gather(jump, response, `0_3`:`2_0`) %>%
  mutate(jump = case_when(jump == '0_3' ~ 'first_end',
                          jump == '1_0'  ~ 'first_start',
                          jump == '1_3' ~ 'second_end',
                          jump == '2_0' ~ 'second_start')) %>%
  separate(jump, into = c('jumpID', 'timepoint')) %>%
  ungroup() %>%
  glmer(response ~ timepoint + jumpID + (1 | target) + (1 + timepoint | networkid) , 
        family = 'binomial',
        contrasts = list(jumpID = contr.sum),
        data = .) %>%
  summary()
```

accuracy increase across initial interactions w/ new partner

```{r}
relevantClicks %>%  
  filter(repnum == 0) %>%
  glmer(correct ~ partnernum + (1  | participantid) + (1 |target),
              family = 'binomial',
              control = glmerControl("bobyqa"),
              data = .) %>%
  summary()
```

```{r}
disconnects <- read_csv('../data/pilot/info.csv') %>%
  rbind(read_csv('../data/pilot1/info.csv')) %>% 
  filter(contents == 'disconnect') %>% pull(details) %>% map_dfr(jsonlite::fromJSON) %>% pull(wID) %>% unique()

disconnects
```
