---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(ggthemes)
library(tidyboot)
library(jsonlite)
```

# Simulation 1.1: Coordination

Plot accuracy for fig in main text

```{r}
d.trajectory.boot <- read_csv('../simulations/cogsci2017/output/arbitrariness_trajectory_discount:0.8_123456789.csv')  %>%
  mutate(repNum = floor(trialNum/2)) %>%
  group_by(speakerAlpha, repNum) %>%
  tidyboot_mean(correct, nboot = 1000)
  
d.trajectory.boot %>%
  filter(repNum < 15) %>%
  mutate(repNum = repNum+1) %>%
  ungroup() %>%
  ggplot(aes(x = repNum, y = empirical_stat, color = factor(speakerAlpha))) +
    geom_line() +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width =0) +
    geom_hline(yintercept = c(.5, 1), linetype = 'dotted') +
    theme_few() +
    scale_x_continuous(breaks =c(1,5,10,15)) +
    theme(aspect.ratio = 2/3, legend.position = 'none') +
    scale_color_colorblind() +
    labs(y = '% accuracy', x = 'repetition #')
ggsave('../writing/journal_manuscript/figures/sec1-convergence.pdf', width = 3, height = 2, unit = 'in')
```

## Examine arbitrariness/path-dependence of meanings

```{r}
read_csv('../simulations/cogsci2017/output/arbitrariness_meaningTest_discount:0.8_123456789.csv') %>%
  left_join(read_csv('../simulations/cogsci2017/output/arbitrariness_trajectory_discount:0.8_123456789.csv')) %>%
  unite(datachunk, intendedName, topSpeakerChoice, topListenerChoice) %>%
  group_by(gameNum) %>%
  mutate(firstdatachunk = first(datachunk)) %>%
  gather(meaning, score,circleScore,squareScore) %>%
  group_by(firstdatachunk, trialNum, word, agentID, meaning) %>%
  mutate(score =exp(score)) %>%
  summarize(score = mean(score)) %>%
  filter(word == 'word1', trialNum < 9) %>%
  ungroup() %>%
  mutate(trialNum = 1 + trialNum,
         meaning = gsub('Score', '', meaning, fixed=TRUE),
         meaning = fct_relevel(meaning, 'square', 'circle'),
         firstdatachunk = fct_relevel(firstdatachunk, 
          'circle_word1_circle', 'square_word1_square', 
          'circle_word2_circle', 'square_word2_square',
          'circle_word1_square', 'square_word1_circle',
          'circle_word2_square', 'square_word2_circle')) %>%
  ggplot(aes(x = trialNum, y = score, fill = factor(meaning))) +
    geom_area(state='identity', alpha = 0.8) +
    facet_grid(firstdatachunk ~ agentID ) +
    scale_fill_manual(values = rev(colorblind_pal()(3))) +
    scale_y_continuous(breaks =c(0,0.5,1)) +
    scale_x_continuous(breaks =c(1,2,3,4,5,6,7,8,9)) +
    theme_few() +
    labs(x = 'trial #', y = 'probability word1 has meaning') +
    theme(strip.text.y = element_text(angle=0))

ggsave('../writing/journal_manuscript/figures/sec1-arbitrariness-raw.pdf')
```

# Simulation 1.2: Efficiency

```{r}
d.efficiency.boot <- read_csv('../simulations/cogsci2017/output/conjunction_trajectory_discount:0.8_123456789.csv') %>%
  mutate(utt_length = str_count(topSpeakerChoice, '_') + 1,
         repNum = floor(trialNum / 2)) %>%
  group_by(repNum) %>%
  tidyboot_mean(utt_length, nboot = 100)

d.efficiency.boot %>%
  mutate(repNum = repNum + 1) %>%
  ggplot(aes(x = repNum, y = empirical_stat)) +
    geom_line() +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), 
                  width = 0, alpha = 0.5) +
    theme_few() +
    theme(aspect.ratio = 2/3) +
    scale_x_continuous(breaks=c(1,2,3,4,5,6))+
    labs(y = '# words', x = 'repetition #')
ggsave('../writing/journal_manuscript/figures/sec1-efficiency.pdf', width = 3, height = 2, unit = 'in')
```

Show example from one game:

```{r}
example.plot.input <- read_csv('../simulations/cogsci2017/output/conjunction_meaningTest_discount:0.8_123456789.csv') %>%
  left_join( read_csv('../simulations/cogsci2017/output/conjunction_trajectory_discount:0.8_123456789.csv')) %>%
  mutate(word1_belief = exp(word1_belief), 
         word2_belief = exp(word2_belief),
         word3_belief = exp(word3_belief),
         word4_belief = exp(word4_belief),
         word1_production = exp(word1_production),
         word2_production = exp(word2_production),
         word1word2_production = exp(word1word2_production),
         word1_cost = -word1_cost,
         word2_cost = -word2_cost,
         word1word2_cost = -word1word2_cost,
         word1_utility = word1_inform + word1_cost,
         word2_utility = word2_inform + word2_cost,
         word1word2_utility = word1word2_inform + word1word2_cost) %>%
  gather(measure, value, starts_with('word')) %>%
  separate(measure, into = c('words', 'measure')) 

example.plot.input %>%
  filter(gameNum == 30) %>%
  filter(measure == 'production') %>%
  spread(words,value) %>%
  mutate(other = 1 - word1 - word2 - word1word2,
         trialNum = trialNum + 1) %>%
  gather(words, value, word1:other) %>%
  mutate(words = fct_relevel(words, 'other', 'word1word2')) %>%
  filter(trialNum < 10) %>%
  ggplot(aes(x = trialNum, y = value, fill = words)) +
    geom_area() +
    #scale_fill_manual(values = rev(colorblind_pal()(3))) +
    scale_fill_colorblind() +
    theme_classic() +
    theme(aspect.ratio = 1/3)+
    scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8,9))+
    labs(x = 'trial #', y = 'S(u | bluecircle)')
ggsave('../writing/journal_manuscript/figures/sec1-convergence_example_production.pdf', 
       width = 6, height = 2, unit = 'in')
```

```{r}
example.plot.input %>%
  filter(gameNum == 30) %>%
  filter(measure == 'belief') %>%
  mutate(words = fct_relevel(words, 'other', 'word1word2'),
         trialNum = trialNum + 1) %>%
  filter(trialNum < 10) %>%
  ggplot(aes(x = trialNum, y = value, color = words)) +
    geom_hline(yintercept = 0.5, linetype = 'dotted') +
    geom_line() +
    scale_color_colorblind() +
    theme_classic() +
    theme(aspect.ratio = 1/3)+
    ylim(0,1) +
    #facet_grid(~ words) +
    scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8,9))+
    labs(x = 'trial #', y = 'P(phi(w) = bluecircle)')
ggsave('../writing/journal_manuscript/figures/sec1-convergence_example_beliefs.pdf', 
       width = 6, height = 2, unit = 'in')
```

```{r}
example.plot.input %>%
  filter(measure %in% c('cost', 'inform', 'utility')) %>%
  filter(gameNum == 30) %>%
  mutate(words = as.factor(words),
         trialNum = trialNum + 1,
         measure = fct_relevel(measure, 'utility', 'inform'),
) %>%
  filter(trialNum < 10) %>%
  ggplot(aes(x = trialNum, y = value, color = words)) +
    geom_line(position = position_dodge(.2)) +
    facet_grid( ~ measure, scales = 'free') +
    #scale_fill_manual(values = rev(colorblind_pal()(3))) +
    #scale_color_colorblind() +
    theme_few() +
    scale_x_continuous(breaks=c(1,3,5,7,9))+
    labs(x = 'trial #', y = 'probability word1 has meaning') +
    theme(aspect.ratio = 1, legend.position = 'none')
ggsave('../writing/journal_manuscript/figures/sec1-convergence_example_values.pdf',
       width = 4, height = 2, unit = 'in')
```

# Appendices: Full grid, arbitrariness

```{r}
d.arbitrariness.all <- read_csv('../simulations/cogsci2017/output/arbitrariness.csv') %>%
  filter(speakerAlpha == listenerAlpha) %>%
  filter(guessingEpsilon == 0.01) %>%
  mutate(repNum = floor(trialNum/2)) %>%
  group_by(speakerAlpha, listenerAlpha, discountFactor, guessingEpsilon, repNum) %>%
  summarize(probCorrect = mean(correct))

d.arbitrariness.all %>%
  ungroup() %>%
  mutate(discountFactor = discountFactor,
         guessingEpsilon = factor(guessingEpsilon),
         alpha = speakerAlpha) %>%
  ggplot(aes(x = repNum, y = probCorrect, 
             color = discountFactor,
             group= discountFactor)) +
    geom_line() +
    geom_hline(yintercept = c(.5, 1), linetype = 'dotted') +
    facet_grid(alpha ~discountFactor) +
    theme_few() +
    theme(aspect.ratio = 1, legend.position = 'none') +
    labs(x = 'repetition #', y = '% accuracy')

ggsave('../writing/journal_manuscript/figures/arbitrariness_grid_raw.pdf', 
       width = 8, height = 7, unit ='in')
```

```{r}
d.conjunction.all <- read_csv('./simulations/cogsci2017/output/conjunction_trajectories.csv') %>%
  mutate(utt_length = str_count(topSpeakerChoice, '_') + 1,
         repNum = floor(trialNum / 2))

d.conjunction.sum <- d.conjunction.all %>%
  group_by(speakerAlpha, listenerAlpha, discountFactor, guessingEpsilon, costWeight, trialNum) %>%
  summarize(empirical_stat = mean(utt_length)) %>%
  ungroup()

d.conjunction.sum %>%
  filter(discountFactor == 0.8) %>%
  filter(speakerAlpha == listenerAlpha) %>%
  filter(!(speakerAlpha %in% c(2,16,64,1024,262144))) %>%
  mutate(discountFactor = factor(discountFactor),
         guessingEpsilon = log10(guessingEpsilon)) %>%
  ggplot(aes(x = trialNum,
             y = empirical_stat,
             color = guessingEpsilon,
             group = interaction(discountFactor, guessingEpsilon))) +
    geom_line() +
    geom_hline(yintercept = c(2,1), linetype = 'dotted', alpha = 0.1) +
    facet_grid(costWeight ~ speakerAlpha) +
    theme_few() +
    ylim(0.8, 2.2) +
    theme(aspect.ratio = 1) +
    labs(y = '# words')

ggsave('./writing/journal_manuscript/figures/conjuction_grid1.pdf', 
       width = 8, height = 6, unit ='in')

d.conjunction.sum %>%
  filter(guessingEpsilon == 0.01) %>%
  filter(speakerAlpha == listenerAlpha) %>%
  filter(!(speakerAlpha %in% c(2,16,64,1024,262144))) %>%
  mutate(discountFactor = as.numeric(discountFactor),
         guessingEpsilon = log10(guessingEpsilon)) %>%
  ggplot(aes(x = trialNum,
             y = empirical_stat,
             color = discountFactor,
             group = discountFactor)) +
    geom_line() +
    geom_hline(yintercept = c(2,1), linetype = 'dotted', alpha = 0.1) +
    facet_grid(costWeight ~ speakerAlpha) +
    theme_few() +
    ylim(0.8, 2.2) +
    scale_color_continuous_tableau('Green') +
    theme(aspect.ratio = 1) +
    labs(y = '# words')

ggsave('./writing/journal_manuscript/figures/conjuction_grid2.pdf', 
       width = 8, height = 6, unit ='in')
```

# Sanity check

Look at raw trajectories of different meanings for each game (change less over time, i.e. stability).

```{r}
meanings %>%
  gather(meaning, score, null,circle,square) %>%
  ggplot(aes(x = trialNum, y = score, group = interaction(gameNum, agentID))) +
    geom_line(alpha = 0.01) +
    facet_grid(meaning~word)
```